name: a2ir
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas>=1.3.0
  - numpy>=1.20.0
  - scikit-learn
  - pytorch
  - transformers
  - sentence-transformers
  - spacy
  - networkx
  - pyyaml
  - langgraph
  - langchain
  - pymisp
  - requests
  - python-dateutil
  - jsonlines
  - rouge-score
  - nltk
  - keybert
  - scipy
  - psutil
  - pynvml
  - clingo
  - pip
  - pip:
      - shap

